"""add is_temp to posts

Revision ID: 0a2f18900528
Revises: 78687db73ea4
Create Date: 2026-01-12 09:09:29.537111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2f18900528'
down_revision: Union[str, Sequence[str], None] = '78687db73ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("is_temp", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.alter_column("posts", "is_temp", server_default=None)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_temp')
    # ### end Alembic commands ###
