"""init

Revision ID: 4bf79e6f5e11
Revises: 
Create Date: 2026-01-11 09:04:03.881217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf79e6f5e11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),

    sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.text("false")),

    sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")),
    
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
